CREATE DATABASE IF NOT EXISTS notewritten;

CREATE TABLE IF NOT EXISTS users (
	id UUID UNIQUE NOT NULL DEFAULT gen_random_uuid(),
	email STRING UNIQUE NOT NULL,
	password STRING NOT NULL
);

CREATE TABLE IF NOT EXISTS notebooks (
	id UUID UNIQUE NOT NULL DEFAULT gen_random_uuid(),
	name STRING NOT NULL,
	user_id UUID NOT NULL REFERENCES users (id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS pages (
	id UUID UNIQUE NOT NULL DEFAULT gen_random_uuid(),
	name STRING NOT NULL,
	user_id UUID NOT NULL REFERENCES users (id) ON DELETE CASCADE,
	notebook_id UUID NOT NULL REFERENCES notebooks (id) ON DELETE CASCADE,
	s3_upload_key STRING UNIQUE NOT NULL
);